project_id = "ukgnvuxdeosrpzvxxvdh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[realtime]
enabled = true
port = 54326