// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knlytzqbcgiadfbdhzjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtubHl0enFiY2dpYWRmYmRoempxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMTc2NDEsImV4cCI6MjA1Mjc5MzY0MX0.rjNfvA2Q51Ode_ACz7Tc52jm0ZocwdTHRsFa5oOpIZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);