// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukgnvuxdeosrpzvxxvdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZ252dXhkZW9zcnB6dnh4dmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2Mzg4OTYsImV4cCI6MjA1MTIxNDg5Nn0.H3zO9ME2vOX-kFaP7qrp9YBlgLlgwgc4K_Tbel47i_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);